/*
	To add a podcast, follow the pattern here.
	In each row is the URL and title of a podcast.
	Put the URL in single quotes, then a comma, then the podcast title in single quotes, then a comma.
	If the title of the podcast has a single quote somewhere in it, replace it with \' (that's "backslash, single quote").
	Make sure that every entry on the list BUT THE LAST has a comma after the podcast title.
	If you put a comma after the last podcast, it won't work!

	To add a separator, add an entry with no URL.

	Podcasts will be listed on the portal page in the order you put them here.
*/

var podcasts = new Array(
'','Comics',
'http://feeds.penny-arcade.com/pa-mainsite', 'Penny Arcade!',
'http://www.rsspect.com/rss/95.xml','Questionable Content',
'','Fiction and Drama',
'http://abbottcostello.libsyn.com/rss/','Abbott & Costello Show Podcast',
'http://agatha.libsyn.com/rss','Agatha Christie Radio Mysteries',
'http://americanpublicmedia.publicradio.org/podcasts/xml/prairie_home_companion/news_from_lake_wobegon.xml','APM: A Prairie Home Companion\'s News from Lake Wobegon',
'http://www.botar.us/botr.xml','botar\'s old time radio',
'http://www.podango.com/feeds/feed.php?pid=416','Boxcars711 Old Time Radio Pod',
'http://xmone.libsyn.com/rss/','X Minus One Podcast',
'http://zerohour.libsyn.com/rss/','Zero Hour Podcast',
'','Gaming',
'http://www.chatterboxgameshow.com/chatterbox.xml', 'ChatterBox Video Game Radio',
'http://feeds.feedburner.com/QJ/PSP','QJ.net: PSP Updates',
'http://feeds.feedburner.com/psp3d','PSP3D',
'','Health and Fitness',
'http://yogadownload.libsyn.com/rss','20 min. Yoga Sessions from YogaDownload.com',
'http://www.fitnessrocks.org/rss','Fitness Rocks',
'','Humor and Entertainment',
'http://feeds.feedburner.com/AnimePulse','Anime Pulse',
'http://www.distortedview.com/show/index.xml','Distorted View: Daily Comedy Podcast',
'http://f6y.ath.cx/dosage/stream.xml', 'I-Doser',
'http://www.z100.com/podcast/PhoneTaps.xml','Phone Taps: Elvis & The Morning Zoo',
'http://feeds.feedburner.com/tsoya','PRI: The Sound of Young America',
'','Literature and Education',
'http://www.npr.org/rss/podcast.php?id=510219','alt.NPR: Poetry Off the Shelf',
'http://www.npr.org/rss/podcast.php?id=510101','APM: Garrison Keillor\'s The Writer\'s Almanac',
'http://www.dancarlin.com/dchh.xml','Hardcore History',
'http://indiefeedpp.libsyn.com/rss','IndieFeed: Performance Poetry',
'http://podictionary.com/?feed=rss2','podictionary: the podcast for word lovers',
'','Music',
'http://www.npr.org/rss/podcast.php?id=510021','alt.NPR: Groove Salad Taste of the Week',
'http://feeds.feedburner.com/IndiefeedAlt/modernRock','IndieFeed: Alternative / Modern Rock Music',
'http://indiefeedelectronicadance.libsyn.com/rss','IndieFeed: Electronica',
'http://indiefeedfolkamericana.libsyn.com/rss','IndieFeed: Indie-Pop',
'http://midi.libsyn.com/rss','midi',
'http://minnesota.publicradio.org/tools/podcasts/song_of_the_day.xml','MPR: The Current Song of the Day',
'http://feeds.feedburner.com/vgdj', 'OC Remix Podcast',
'http://www.kpikemusic.com/podcast/VibeCast.xml','The VibeCast - indie music podcast with Kevin Pike',
'','News',
'http://rss.cnn.com/rss/cnn_topstories.rss','CNN: Top Stories',
'http://www.foxnews.com/xmlfeed/rss/0,4313,0,00.rss','Fox News latest stories',
'http://www.geeknewscentral.com/podcast.xml','Geek News Central',
'http://podcast.nationalgeographic.com/ng-news/','National Geographic News',
'http://www.theskepticsguide.org/rss.xml','The Skeptic\'s Guide To The Universe',
'','NPR',
'http://www.npr.org/rss/podcast.php?id=510208','NPR: Car Talk',
'http://www.npr.org/rss/podcast.php?id=510097','NPR: Car Talk\'s Call of the Week',
'http://www.npr.org/rss/podcast.php?id=700000','NPR: Driveway Moments',
'http://www.npr.org/rss/podcast.php?id=510184','NPR: Intelligence Squared',
'http://www.npr.org/rss/podcast.php?id=510067','NPR: Justice Talking',
'http://www.npr.org/rss/podcast.php?id=500000','NPR: Most E-Mailed Stories',
'http://www.npr.org/rss/podcast.php?id=1090', 'NPR: Story of the Day',
'http://www.npr.org/rss/podcast.php?id=510095','NPR: Tell Me More',
'http://www.npr.org/rss/podcast.php?id=4538138','NPR: This I Believe',
'http://www.npr.org/rss/podcast.php?id=35','NPR: Wait Wait... Don\'t Tell Me!',
'http://www.npr.org/rss/podcast.php?id=1056','NPR: World Story of the Day',
'','Philosophy',
'http://philosophybites.libsyn.com/rss','Philosophy Bites',
'http://feeds.feedburner.com/PhilosophyPodcast','The Philosophy Podcast',
'','Politics',
'http://www.democracynow.org/podcast.xml','Democracy Now! Audio',
'','Religion',
'http://www.npr.org/rss/podcast.php?id=1016','NPR: Religion',
'http://feeds.feedburner.com/dailyaudiobible','One Year Audio Bible',
'http://www.urbandharma.org/podcast/podcast.xml','Urban Dharma',
'http://feeds.feedburner.com/zencast','Zencast',
'','Science and Tech',
'http://www.welltopia.com/Podcasts/feed.xml','Absolute Science',
'http://www.hak5.org/rss/ipod.xml','Hak5: Trust Your Technolust',
'http://www.npr.org/rss/podcast.php?id=1019','NPR: Technology',
'http://rss.slashdot.org/Slashdot/slashdot','Slashdot',
'','Self-Help',
'http://zigziglar.libsyn.com/rss','Inspiring Words of Encouragement',
'http://violetblue.libsyn.com/rss','open source sex',
'http://feeds.feedburner.com/xyonthefly','X & Y On The Fly--Dating Podcast  LISTEN:  289-466-5002'
);
